config/routes.rb
CrescentStore::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :daily_expenses

  resources :reports do
    collection do
      post :create_consumer
    end
  end
  resources :stores, :only => :show

  resources :homes, :only => :index
  resources :products
  resources :report_items

  devise_for :users

  root :to => 'homes#index'

end

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Crescent</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= @product_tab %>"><%= link_to 'Products', products_path %></li>
        <li class="<%= @report_tab %>"><%= link_to 'Reports', reports_path %></li>
        <li class="<%= @daily_expense_tab %>"><%= link_to 'Daily Expense', daily_expenses_path %></li>

      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
        <%= form_tag(products_path, :method => :get) do %>
            <%= text_field_tag :search, params[:search],
                               {:class => "form-control", :placeholder => "By name"} %>
            <button type="submit" class="btn btn-default">Search</button>
        </div>
        <% end %>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><span class="label label-warning"><%= current_user.store.name %></span></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= "Hello #{current_user.first_name} #{current_user.last_name}!" %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, :method=> :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>