config/routes.rb
CrescentStore::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :daily_expenses

  resources :reports do
    collection do
      post :create_consumer
    end
  end
  resources :stores, :only => :show

  resources :homes, :only => :index
  resources :products
  resources :report_items

  devise_for :users

  root :to => 'homes#index'

end

app/models/product.rb
require 'file_size_validator'
class Product < ActiveRecord::Base
  belongs_to :store
  has_many :reports
  has_one :attribute

  mount_uploader :image, ImageUploader
  validates :image,
            :file_size => { :maximum => 0.5.megabytes.to_i}

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @product_tab = 'active'
    @products = current_user.store.products
    @products = @products.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product_tab = 'active'
  end

  # GET /products/new
  def new
    @product_tab = 'active'
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product_tab = 'active'
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        @product.store_id = params[:product][:stores][:store_id] if params[:product][:stores][:store_id].present?
        @product.save
        @attribute = Attribute.new(:product_id => @product.id, :size => params[:product][:attributes][:size], :color => params[:product][:attributes][:color], :category => params[:product][:attributes][:category], :price => params[:product][:attributes][:price])
        @attribute.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        @product.store_id = params[:product][:stores][:store_id] if params[:product][:stores][:store_id].present?
        @product.save
        @attribute = Attribute.find_by_product_id @product.id
        @attribute.size= params[:product][:attributes][:size]
        @attribute.color= params[:product][:attributes][:color]
        @attribute.category= params[:product][:attributes][:category]
        @attribute.price= params[:product][:attributes][:price]
        @attribute.save
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :code, :quantity, :price, :size, :color, :category, :store_id, :image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_categories
    products = ["Shoe","Moneybag","Handbag"]
  end
  def store_locations
    stores = []
    Store.all.each do |store|
      stores << store.location
    end
    return stores
  end
end

app/views/products/_form.html.erb
<%= form_for @product, :html => {:multipart => true} do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= f.fields_for :attributes do |u| %>
        <%= f.fields_for :stores do |s| %>
        <div class="container">
          <div class="jumbotron">
          <form class="form-horizontal" role="form">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Product Name</label>
              <div class="col-sm-10 col-md-10">
                <%= f.text_field :name, :class=>"form-control", :id=>"inputEmail3", :placeholder=>"Product Name" %>
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Product Code</label>
              <div class="col-sm-10 col-md-10">
                <%= f.text_field :code, :class=>"form-control", :id=>"inputEmail3", :placeholder=>"Product Code" %>
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 col-md-2control-label">Product Category</label>
              <div class="col-sm-10 col-md-10">
                <%= u.select :category, product_categories, prompt: 'Select a Category', :class=>"form-control" %>
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 col-md-2control-label">Product Price</label>
              <div class="col-sm-10 col-md-10">
                <%= u.text_field :price, :class=>"form-control", :id=>"inputEmail3", :placeholder=>"Product Price" %>
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Product Size</label>
              <div class="col-sm-10 col-md-10">
                <%= u.text_field :size, :class=>"form-control", :id=>"inputEmail3", :placeholder=>"Product Size" %>
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Product Color</label>
              <div class="col-sm-10 col-md-10">
                <%= u.text_field :color, :class=>"form-control", :id=>"inputEmail3", :placeholder=>"Product Color" %>
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Product Quantity</label>
              <div class="col-sm-10 col-md-10">
                <%= f.text_field :quantity, :class=>"form-control", :id=>"inputEmail3", :placeholder=>"Product Quantity" %>
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Product Quantity</label>
              <div class="col-sm-10 col-md-10">
                <%= s.select :store_id, Store.all.collect{|p| [p.name, p.id] }, :class=>"form-control"%>
              </div>
            </div>

            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 col-md-2 control-label">Product Image</label>
              <div class="col-sm-10 col-md-10">
                <%= f.file_field :image, :class => "file_1" %>
              </div>
            </div>
            <div style="padding: 10px"><%= f.submit 'Save Product', :class=>"btn btn-success" %></div>
            <%= link_to 'Back', products_path, :class => "pull-right" %>
          </form>
          </div>
        </div>
        <% end %>
    <% end %>
<% end %>

app/views/products/edit.html.erb
<div class="container panel panel-primary">
  <div class="panel-body">
    <h1>Edit Product</h1>
  </div>
</div>


<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

<style>
    .container{
        padding: 0px;
    }
    .panel-primary{
        background: #428BCA;
    }
</style>

app/views/products/index.html.erb
<!--<h1>Listing products</h1>-->
<div class="container">
  <div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">Products Available in Store</div>
    <div class="panel-body">
      <p>Here is the list of all products which are available in this store. Press 'Add Product' button to sell a product and create a invoice!
        You are also able to remove product from the invoice, if consumer not interested to buy this product. Then press 'Sell all Seleted Products' button to procced next.
      </p>
    </div>
  </div>
  <br><br>
  <table class="table table-striped table-bordered">
      <thead>
      <tr>
        <th>Product Image</th>
        <th>Product Name</th>
        <th>Product Code</th>
        <th>Store</th>
        <th>Product Category</th>
        <th>Product Price</th>
        <th>Product Quantity</th>
        <th>Product Size</th>
        <th>Product Color</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @products.each do |product| %>

          <tr>
            <td class="list_description">
              <%= image_tag product.image_url(:thumb) unless product.image.blank? %>
            </td>
            <td class="list_description">
              <%= product.name %>
            </td>
            <td class="list_description">
              <%= product.code %>
            </td>
            <td class="list_description">
              <%= product.store.location %>
            </td>
            <td class="list_description">
              <%= product.attribute.category %>
            </td>
            <td class="list_description">
              <%= product.attribute.price %>
            </td>
            <td class="list_description">
              <span class="label <%= product.quantity > 10 ? 'label-success' : 'label-danger' %>"><%= product.quantity %></span>
            </td>
            <td class="list_description">
              <%= product.attribute.size %>
            </td>
            <td class="list_description">
              <%= product.attribute.color %>
            </td>
            <td class="list_description" id="add-product-<%= product.id %>">
              <% unless session[:report_id].nil? %>
                <% report_item = ReportItem.where(product_id: product.id, report_id: session[:report_id]) %>
                <% if report_item.present? %>
                  <%= link_to 'Remove Product', report_item.first, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, :class=>"btn btn-danger" %>
                <% else %>
                  <%= button_to 'Add Product', report_items_path(product_id: product), remote: true, :class => 'btn btn-primary btn-sm' %>
                <% end %>
              <% else %>
                  <%= button_to 'Add Product', report_items_path(product_id: product), remote: true, :class => 'btn btn-primary btn-sm' %>
              <% end %>

              <!--<div class="checkbox">-->
                <!--<label>-->
                  <!--<%#= check_box_tag "product_#{product.id}", 1 ,:onclick => "addToReport(#{product.id})" %>-->
                  <!--<b>Add to Sell</b>-->
                <!--</label>-->
              <!--</div>-->
            </td>
            <td class="list_actions">
              <%= link_to 'Show', product %>
              <br/>
              <%= link_to 'Edit', edit_product_path(product) %>
              <br/>
              <%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>
  <div class="row">
      <div class="col-md-8">
        <%= link_to 'New Product', new_product_path, :class => 'btn btn-success btn-lg', :role => "button" %>
      </div>
      <div class="col-md-4" id="sell-button">
        <% report = Report.where(id: session[:report_id]) %>
        <%= link_to 'Sell All Selected Products', (report.blank? ? '#' : edit_report_path(report.first)), :class => 'btn btn-large btn-block btn-warning pull-right', :role => "button" %>
      </div>
  </div>
  <br><br>
  <%= will_paginate @products, :renderer=> 'BootstrapPagination::Rails' %>
</div>

app/views/products/new.html.erb
<div class="container panel panel-primary">
  <div class="panel-body">
    <h1>New Product</h1>
  </div>
  <div class="panel-footer">Create a new product</div>
</div>

<%= render 'form' %>


<style>
  .container{
      padding: 0px;
  }
  .panel-primary{
      background: #428BCA;
  }
</style>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image_url(:profile) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.attribute.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.attribute.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.attribute.size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.attribute.color %>
</p>

<p>
  <strong>Available In Store:</strong>
  <%= Store.where(id: @product.store_id).first.location %>
</p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>