config/routes.rb
CrescentStore::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :daily_expenses

  resources :reports do
    collection do
      post :create_consumer
    end
  end
  resources :stores, :only => :show

  resources :homes, :only => :index
  resources :products
  resources :report_items

  devise_for :users

  root :to => 'homes#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :product
  belongs_to :store
  has_one :consumer
  has_many :report_items

  def add_product(product_id)
    current_item = report_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = report_items.build(product_id: product_id)
      #current_item.price = current_item.product.attribute.price
    end
    current_item
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @report_tab = 'active'

    # Chart One ===================
    @reports = current_user.store.reports
    @todays_reports = current_user.store.reports.where('created_at > ?', 1.days.ago)
    @chart_one = []
    @todays_reports.each do |report|
      time = report.created_at + 6.hours #Lame technique. Will be fixed soon. This is only of Bangladesh and +6 TimeZone
      @chart_one << ["[Date.UTC(#{time.year}, #{time.month}, #{time.day}, #{time.hour}, #{time.min}), #{calculate_total_price_of_a_report(report)}]"]
    end
    @chart_one = @chart_one.join(', ')

    # Chart Two ===================
    @products = current_user.store.products
    @chart_two = []
    @products.each do |product|
      @chart_two << ["['#{product.attribute.category}', #{product.quantity}]"] unless product.attribute.category = 'Shoe'
      @chart_two << "{name: 'Shoe',y: #{product.quantity}, sliced: true,selected: true}" if product.attribute.category = 'Shoe'
    end
    @chart_two = @chart_two.join(', ')
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report_tab = 'active'
  end

  # GET /reports/new
  def new
    @report_tab = 'active'
    @report = Report.new
    @consumer = Consumer.new
  end

  # GET /reports/1/edit
  def edit
    @report_tab = 'active'
  end

  # POST /reports
  # POST /reports.json
  def create
    @consumer = Consumer.create!(consumer_params)
    #params[:consumer_id] = @consumer.id
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        @report.product.quantity = @report.product.quantity - @report.quantity
        @report.product.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    @report.report_items.each do |report_item|
      quantity = params["report_item_#{report_item.id}"].to_i
      report_item.quantity = quantity
      report_item.save
      product = Product.find report_item.product_id
      product.quantity = product.quantity - quantity
      product.save!(:validate => false)
    end
    @consumer = Consumer.create!(consumer_params)
    respond_to do |format|
      if @report.update(report_params)
        @report.consumer_id = @consumer.id
        @report.save
        session[:report_id] = nil
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  def calculate_total_price_of_a_report(report)
    total_price = 0
    report.report_items.each do |item|
      product = Product.find item.product_id
      total_price += product.attribute.price
    end

    return (total_price + (total_price * 0.15))
  end

  def create_consumer
    puts 'Hello'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      #params[:report]
      params.require(:report).permit(:consumer_id, :seller_id, :product_id, :quantity, :consumer_attributes => [:first_name, :last_name, :email, :phone, :address])
    end

    def consumer_params
      params[:report][:consumers].permit(:first_name, :last_name, :email, :phone, :address)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def calculate_total_price(report)
    total_price = 0
    report.report_items.each do |item|
      product = Product.find item.product_id
      total_price += product.attribute.price
    end

    return (total_price + (total_price * 0.15))
  end
  def calculate_total_quantity(report)
    total_quantity = 0
    report.report_items.each do |item|
      total_quantity += item.quantity
    end
    return total_quantity
  end
end

app/views/reports/_form.html.erb
<%# product = Product.find params[:product] %>
<% report = Report.find session[:report_id] %>
<div style="max-width: 960px; margin: 0 auto">
  <h1>Invoice</h1>
  <%= form_for(@report) do |f| %>
      <% if @report.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

            <ul>
              <% @report.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="row" style="border-bottom: 2px solid gray">
        <div class="col-md-6"><h4><b>OUR DETAILS</b></h4></div>
        <div class="col-md-6 text-right"><h4><b>INVOICE DETAILS</b></h4></div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <p><b><%= report.store.name %></b></p>
          <p><%= report.store.email %></p>
          <p><%= report.store.phone %></p>
          <p><%= report.store.location %></p>
          <%#= f.hidden_field :store_id, :value =>product.store.id %>
          <%#= f.hidden_field :product_id, :value =>product.id %>
          <%= f.hidden_field :seller_id, :value =>current_user.id %>
          <%= f.hidden_field :consumer_id %>
        </div>
        <div class="col-md-6 text-right">
          <p>Invoice id #<b><%= session[:report_id] %></b></p>
          <p>Invoice Date: <b><%= report.created_at.strftime("%B %d, %Y") %></b></p>
        </div>
      </div>

      <br><br>

      <div class="row">
        <div class="col-md-6">
          <h4><b>BILLING DETAILS</b></h4>
          <p>Mahbub Rony</p>
          <p>rony.cse36@gmail.com</p>
          <p>+8801717690796</p>
          <p>312, Ahmed Nagar <br> Mirpur, Dhaka</p>
        </div>
        <div class="col-md-6">
          Please insert consumer details ...
          <%= f.fields_for :consumers do |ff| %>
          <!--<form role="form" id="consumer-form" method="post" action="/reports/create_consumer" data-remote='true'>-->
            <div class="form-group">
              <label>First Name:</label>
              <!--<input type="text" class="form-control" id="first-name" placeholder="Enter First Name">-->
              <%= ff.text_field :first_name, :class=>"form-control", :id=>"first-name", :placeholder=>"Enter First Name" %>
              <label>Last Name:</label>
              <!--<input type="text" class="form-control" id="last-name" placeholder="Enter Last Name">-->
              <%= ff.text_field :last_name, :class=>"form-control", :id=>"last-name", :placeholder=>"Enter Last Name" %>
            </div>
            <div class="form-group">
              <label>Email</label>
              <%= ff.text_field :email, :class=>"form-control", :id=>"email", :placeholder=>"Enter Email" %>
            </div>
            <div class="form-group">
              <label>Phone</label>
              <%= ff.text_field :phone, :class=>"form-control", :id=>"phone", :placeholder=>"Enter Phone Number" %>
            </div>
            <div class="form-group">
              <label>Address</label>
              <!--<textarea class="form-control" id="address" rows="3"></textarea>-->
              <%= ff.text_area :address, :class=>"form-control", :id=>"address", :placeholder=>"Enter Address" %>
              <%= ff.hidden_field :report_id%>
            </div>
            <!--<button type="submit" class="btn btn-default">Submit Consumer</button>-->
            <%#= ff.submit 'Submit Consumer', :class=> 'btn btn-default' %>
          <!--</form>-->
          <% end %>
        </div>
      </div>

      <div>
        <h2>ITEMS</h2>
        <table class="table">
          <th>#</th>
          <th>WHAT?</th>
          <th>OPTIONS?</th>
          <th>HOW MANY?</th>
          <th class="text-right">AMOUNT?</th>
          <% report.report_items.each_with_index do |report_item, index| %>
          <% product = Product.find report_item.product_id %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= "#{product.name} #{product.code}" %></td>
            <td><%= "#{product.attribute.color}, Size: #{product.attribute.size}" %></td>
            <td><%= text_field_tag "report_item_#{report_item.id}",'', :onkeyup=>"calculatePrice(#{report_item.id}, #{product.attribute.price} )" %></td>
            <td class="text-right"><span class="cart_item report_item_<%=report_item.id%>">0.00</span> BDT</td>
          </tr>
          <% end %>
          <!-- Button trigger modal -->
          <!--<button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">-->
            <!--Launch demo modal-->
          <!--</button>-->
          <!--Fixed tr-->
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right"><b>Sub-Total:</b> <spna id='sub-total'>0.00</spna> BDT</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right"><b>15% VAT:</b> <span id="vat">0.00</span> BDT</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right"><b style="font-size: 15px">Order Total:</b> <span id="total">0.00</span> BDT</td>
          </tr>
          <!--End of fixed tr-->
        </table>
        <!--<table class="table">-->

        <!--</table>-->
      </div>

      <br>

      <div class="actions">
        <%= f.submit 'Sell and Create Invoice', :class=>"btn btn-default" %>
      </div>
  <% end %>
</div>

<!-- Modal -->
<!--<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">-->
  <!--<div class="modal-dialog">-->
    <!--<div class="modal-content">-->
      <!--<div class="modal-header">-->
        <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>-->
        <!--<h4 class="modal-title" id="myModalLabel">Modal title</h4>-->
      <!--</div>-->
      <!--<div class="modal-body">-->
        <!--...-->
      <!--</div>-->
      <!--<div class="modal-footer">-->
        <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
        <!--<button type="button" class="btn btn-primary">Save changes</button>-->
      <!--</div>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->
<script>
//    $('form#consumer-form').submit(function() {
//        var valuesToSubmit = $(this).serialize();
//        $.ajax({
//            url: $(this).attr('action'), //sumbits it to the given url of the form
//            data: valuesToSubmit
//        }).success(function(json){
//                   alert('Suc'); //act on result.
//        });
//        return false; // prevents normal behaviour
//    });
//        $("#pquantity").keyup(function(){
//            alert('Hello');
//            var quantity = $(this).text();
//            var price = <%#= product.attribute.price %>;
//            alert(price);
//            var without_vat = quantity * price;
//            alert(without_vat)
//            var with_vat = without_vat + (without_vat *.15); // 15% vat
//            alert(with_vat);
//            $('#total').text = 30000;
//        })

function calculatePrice(report_id, price)
{
    var quantity = document.getElementById('report_item_'+report_id).value;
    if($.isNumeric(quantity)){
        var per_product_cost = parseFloat(price * quantity).toFixed(2);
        document.getElementsByClassName('report_item_'+report_id)[0].innerHTML = per_product_cost;

        var all_elements = document.getElementsByClassName('cart_item');
        var sub_grand_total = 0
        for(var i=0, max= all_elements.length; i < max; i++){
            sub_grand_total += parseInt(all_elements[i].innerHTML);
        }
        document.getElementById('sub-total').innerHTML = parseFloat(sub_grand_total).toFixed(2);
        document.getElementById('vat').innerHTML = parseFloat(sub_grand_total * .15).toFixed(2);
        document.getElementById('total').innerHTML = parseFloat(sub_grand_total + (sub_grand_total * .15)).toFixed(2);
    }

}
</script>

app/views/reports/edit.html.erb
<%= render 'form' %>
<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<div style="width: 80%; margin: 0 auto">
    <div class="row">
      <div class="col-md-6"><div id="todays-sell" style="min-width: 310px; height: 400px; margin: 0 auto"></div></div>
      <div class="col-md-6"><div id="available-product" style="min-width: 310px; height: 400px; margin: 0 auto"></div></div>
    </div>
    <!--<div class="row"><div id="todays-sold" style="min-width: 310px; height: 400px; margin: 0 auto"></div></div>-->
  <br><br>

  <h2>All Reports</h2>
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>Seller Name</th>
      <th>Consumer Name</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th>Sold At</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @reports.each_with_index do |report, index| %>
        <% seller = User.find report.seller_id %>
        <% consumer = Consumer.find report.consumer_id %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= "#{seller.first_name} #{seller.last_name}" %></td>
          <td><%= "#{consumer.first_name} #{consumer.last_name}" %></td>
          <td><%= calculate_total_quantity(report) %></td>
          <td><%= calculate_total_price(report) %></td>
          <td><%= report.created_at.strftime("%B %d, %Y") %></td>
          <td><%= link_to 'Show Details', report, :class=>"btn btn-info" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<script>
//  $(document).load(function(){location.reload();})
    $(function () {
        $('#todays-sell').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Product Sold by Time'
            },
            subtitle: {
                text: "Source: <%= current_user.store.name %>"
            },
            xAxis: {
                title: {
                    enabled: true,
                    text: 'Hours of the Day'
                },
                type: 'datetime',

                dateTimeLabelFormats : {
                    hour: '%I %p',
                    minute: '%I:%M %p'
                }
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Product Price'
                }
            },
            tooltip: {
                formatter: function() {
                    return ''+
                            "" +
                            'Time: '+ Highcharts.dateFormat('%I:%M %p', this.x) + ' & Sold Price:' + this.y;
                }
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: '<%= current_user.store.name %>',
                data: [<%= @chart_one %>]
            }]
        });
    });

    $(function () {
        $('#available-product').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'Available Product by Type'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
            series: [{
                type: 'pie',
                name: 'Product Type',
                data: [ <%= @chart_two.html_safe %> ]
            }]
        });
    });

</script>

<%#= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<div style="position: fixed; right: 10.5%">
  <%= link_to '<span class="glyphicon glyphicon-print"></span> Print'.html_safe, 'javascript:void(0)', :onclick=>"window.print()", :class=>'btn btn-default btn-lg pull-right' %>
</div>
<div id="printable">
  <h1>Invoice</h1>
  <div class="row" style="border-bottom: 2px solid gray">
        <div class="col-md-6"><h4><b>OUR DETAILS</b></h4></div>
        <div class="col-md-6 text-right"><h4><b>INVOICE DETAILS</b></h4></div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <p><b><%= @report.store.name %></b></p>
          <p><%= @report.store.email %></p>
          <p><%= @report.store.phone %></p>
          <p><%= @report.store.location %></p>
        </div>
        <div class="col-md-6 text-right">
          <p>Invoice id #<b><%= @report.id %></b></p>
          <p>Invoice Date: <b><%= @report.created_at.strftime("%B %d, %Y") %></b></p>
        </div>
      </div>

      <br><br>

      <div class="row">
        <div class="col-md-6">
          <% @consumer = Consumer.find @report.consumer_id %>
          <h4><b>BILLING DETAILS</b></h4>
          <p><%= @consumer.first_name %> <%= @consumer.last_name %></p>
          <p><%= @consumer.email %></p>
          <p><%= @consumer.phone %></p>
          <p><%= @consumer.address %></p>
        </div>
        <div class="col-md-6">
          <div id="paid-logo"><%= image_tag 'paid.png' %></div>
        </div>
      </div>

      <div>
        <h2>ITEMS</h2>
        <table class="table">
          <th>#</th>
          <th>WHAT?</th>
          <th>OPTIONS?</th>
          <th>HOW MANY?</th>
          <th class="text-right">AMOUNT?</th>
          <% sub_grand_total = 0 %>
          <% @report.report_items.each_with_index do |report_item, index| %>
              <% product = Product.find report_item.product_id %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= "#{product.name} #{product.code}" %></td>
                <td><%= "#{product.attribute.color}, Size: #{product.attribute.size}" %></td>
                <td><%= report_item.quantity %></td>
                <td class="text-right"><span><%= (product.attribute.price * report_item.quantity).round(2) %> BDT</span></td>
                <% sub_grand_total += (product.attribute.price * report_item.quantity).to_f.round(2) %>
              </tr>
          <% end %>
          <!-- Button trigger modal -->
          <!--<button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">-->
          <!--Launch demo modal-->
          <!--</button>-->
          <!--Fixed tr-->
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right"><b>Sub-Total:</b> <spna id='sub-total'><%= sub_grand_total.to_f.round(2) %> BDT</spna></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right">
              <b>15% VAT:</b>
              <span id="vat"><%= (sub_grand_total * 0.15).to_f.round(2) %> BDT</span>
            </td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right">
              <b style="font-size: 15px">Order Total:</b>
              <span id="total"><%= (sub_grand_total + (sub_grand_total * 0.15)).to_f.round(2) %> BDT</span>
            </td>
          </tr>
          <!--End of fixed tr-->
        </table>
        <!--<table class="table">-->

        <!--</table>-->
      </div>

      <br>
</div>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>